<div class="mws-panel grid_8">
	<div class="mws-panel-header">
	    <span class="mws-i-24 i-pencil">Editor de Venda</span>
	</div>
	<div class="mws-panel-body">
<?php 
    if(!empty($this->registro["codigo"])):
?>	
	    <div class="mws-wizard clearfix">
            <ul>                
                <li id="cadastro" class="current aba">
                    <a href="javascript://" class="mws-ic-16 ic-pencil" title="Dados Cadastrais">Dados Cadastrais</a>
                </li>                
                <li id="produto" class="aba">
                    <a class="mws-ic-16 ic-images" href="javascript://" title="Produtos">Produtos/Serviços</a>
                </li>                                             
                <li id="receber" class="aba">
                    <a class="mws-ic-16 ic-money" href="javascript://" title="Contas a Receber">Contas a Receber</a>
                </li>                
            </ul>
        </div>
<?php 
    endif;
?>        	    
    	<form action="<?php echo $this->url(array("controller"=>$this->controllerName, "action"=>"salvar-cadastro", "module"=>"admin"));?>" class="mws-form" id="formCadastro">		
    		<input type="hidden" id="cadastro-iframe" value="<?php echo $this->iframe; ?>" />		
    		<input id="codigo" type="hidden" name="codigo" value="<?php echo $this->registro["codigo"]; ?>" />
    		<div class="abaContent current cadastro">
        		<div class="mws-form-inline">                                
    			    <div class="mws-form-cols clearfix">				
    			        
<?php if(!empty($this->registro["codigo"])): ?>
    			        <div class="mws-form-col-1-8 alpha">
            			    <label>Código da Venda</label>
            			    <div class="mws-form-item large">
            					<input disabled="disabled" value="<?php echo $this->registro["codigo"]; ?>" type="text" class="mws-textinput" maxlength="100">
            			    </div>
            			</div>
<?php endif; ?>
    			        
            			<div class="mws-form-col-2-8 alpha">
            			    <label>Usuário</label>
            			    <div class="mws-form-item large">
            					<input disabled="disabled" value="<?php echo $this->usuario["nome"]; ?>" type="text" class="mws-textinput" name="usuario" maxlength="100">
            			    </div>
            			</div>
        			    
            			<div class="mws-form-col-1-8 alpha">
            			    <label>Data da Venda</label>
            			    <div class="mws-form-item large">
            					<input value="<?php echo (!empty($this->registro["datavenda"]))?$this->data($this->registro["datavenda"]):date('d/m/Y'); ?>" type="text" class="mws-textinput data" name="datavenda">
            			    </div>
            			</div>
            			
                        <div class="mws-form-col-4-8 alpha">				    
                    	    <label>* Contratante</label> 				    					    
                    	    <div class="mws-form-item large">				    	
                    			<select id="cliente" class="chzn-select" name="cliente" style="width: 75%;">
                    				<option value="">Selecione o cliente</option>	
<?php 
if(count($this->clientes) > 0):
    $selected = '';
	foreach($this->clientes as $cliente):	
		$selected = ($this->registro["cliente"] == $cliente["codigo"])?"selected='selected'":"";
	    $cpfCnpj = ($cliente["tipopessoa"] == "F")?" CPF - ".$cliente["cpf"]:" CNPJ - ".$cliente["cnpj"];	
?>                        
            						<option <?php echo $selected; ?> value="<?php echo $cliente["codigo"];?>">
            							<?php echo $cliente["nome"].$cpfCnpj;?>
            						</option>
<?php		
	endforeach;
endif;
?>													
            					</select>
            					<ul id="icons-16">
            					    <li id="addCliente" style="margin: 0 4px;display: none;" title="Incluir novo cliente" class="mws-ic-16 ic-add adicionarCliente"></li>
            					    <li id="viewCliente" style="margin: 0 4px;" title="Ver dados do cliente" class="mws-ic-16 ic-magnifier adicionarCliente"></li>
            					</ul>						
            			    </div>
            			</div>
    			                    			    						        		
            	    </div>        	   
            	</div>            	
    	    </div>
        	
        	<div class="produto abaContent">
    	         <?php    	           
    	            echo $this->partial("/venda/produto.phtml", array("moedas"=>$this->moedas));
                ?>    
    	    </div>
    	        	    
        	<div class="receber abaContent">
    	        <?php
    	            $vendaRecebimentos = array();
        	        if(!empty($this->registro["codigo"])):
        	            $vendaRecebimentos = $this->registro->findDependentRowSet("Model_VendaAReceber",null,$this->registro->select()->order("parcela ASC"));
        	        endif;
    	            echo $this->partial("/venda/pagamento.phtml", array("vendaPagamentos"=>$vendaRecebimentos));
                ?>
    	    </div>
        	
<?php 
    if(!empty($this->registro["codigo"])):
?>        	
        	<div class="mws-form-cols clearfix" style="background: #E3E2E2;">
            	<div class="mws-form-col-2-8 alpha">
            		<label><strong>Total em Produtos (<span class="moeda"></span>)</strong></label>
            		<div class="mws-form-item large">
            			<input name="valortotal" id="valorTotal" value="<?php echo $this->NumeroParaMoeda($this->registro["valortotal"]); ?>" disabled="disabled" type="text" class="mws-textinput dinheiro">        					
            		</div>
            	</div>
            	            	
            	<div class="mws-form-col-2-8 alpha">
            		<label><strong>Valor Pago (<span class="moeda"></span>)</strong></label>
            		<div class="mws-form-item large">
            			<input id="totalValorPago" disabled="disabled" type="text" class="mws-textinput dinheiro">        					
            		</div>
            	</div>
            	
            	<div class="mws-form-col-2-8 alpha">
            		<label><strong>Saldo Devedor (<span class="moeda"></span>)</strong></label>
            		<div class="mws-form-item large">
            			<input id="saldoDevedor" disabled="disabled" type="text" class="mws-textinput">        					
            		</div>
            	</div> 
            	   			
            	<div class="mws-form-col-2-8 alpha">
            		<label><strong>Saldo Devedor (R$)</strong></label>
            		<div class="mws-form-item large">
            			<input id="saldoDevedorReal" disabled="disabled" type="text" class="mws-textinput">        					
            		</div>
            	</div>    			
            </div>
<?php 
    endif;
?>            
            
            <div class="mws-button-row">
                    <input type="submit" class="mws-button red" value="Enviar" />
<?php 
    if(!$this->iframe):
?>    			
                    
                    <input id="voltar" type="reset" class="mws-button gray" value="Voltar" onclick="location.href='<?php echo $this->url(array("controller"=>$this->controllerName, "action"=>"index", "module"=>"admin"),null,true);?>'" />
<?php 
    else:
?>
                    <input type="reset" class="mws-button gray" value="Fechar" onclick="window.parent.$('#dialog').dialog('close');" />
<?php
    endif; 
?> 
    		</div> 
            	
    	</form>    	
	</div>
</div>

<!-- Box pagamento -->
<div style="display: none;" id="dialog-pagamento" title="Receber">
	<div id="retorno-dialog-pagamento" style="margin-top:0px;margin-bottom: 5px;" class="mws-form-message warning"></div>
	<div class="mws-panel-body">
		<form action="javascript://" class="mws-form" id="formPagamento">														
			<input name="venda" type="hidden" value="<?php echo $this->registro["codigo"]; ?>">
			<input id="codigoRecebimento" name="codigo" type="hidden" value="">
			<div class="mws-form-block"> 
			    <div class="mws-form-row">
					<label>Data Pagamento</label>
					<div class="mws-form-item large">
						<input value="<?php echo date("d/m/Y"); ?>" name="datapagamento" id="datapagamento" type="text" class="mws-textinput">
					</div>
				</div>
					                               
			    <div class="mws-form-row">
					<label>Câmbio (R$)</label>
					<div class="mws-form-item large">
						<input id="valorCambioReceber" value="" name="valorcambioreceber" type="text" class="mws-textinput dinheiro">
					</div>
				</div>	
				                               
				<div class="mws-form-row">
					<label>Valor a Receber (R$)</label>
					<div class="mws-form-item large">
					    <input type="hidden" name="valorreceber">
						<input id="valorReceber" disabled="disabled" type="text" class="mws-textinput dinheiro">
					</div>
				</div>			
							
				<div class="mws-form-row">
					<label>Valor Recebido (R$)</label>
					<div class="mws-form-item large">
						<input name="valorpago" id="valorpago" type="text" class="mws-textinput dinheiro">
					</div>
				</div>			
				<div class="mws-form-row">
					<label>Valor do Troco (R$)</label>
					<div class="mws-form-item large">
						<input name="valortroco" type="hidden" value="0,00" class="mws-textinput dinheiro">
						<input disabled="disabled" id="valortroco" type="text" value="0,00" class="mws-textinput dinheiro">
					</div>
				</div>																
		    </div>		    
		</form>
	</div>
</div>
<!-- End pagamento -->



 <!-- Box reembolso -->
<div style="display: none;" id="dialog-reembolso" title="Reembolso">
    <div id="retorno-dialog-reembolso" style="margin-top:0px;margin-bottom: 5px;" class="mws-form-message warning"></div>	
	<div class="mws-panel-body">
		<form action="javascript://" class="mws-form" id="formReembolso">											
			<input name="venda" type="hidden" value="<?php echo $this->registro["codigo"]; ?>">
			<input name="valorpago" type="hidden">
			<input id="codigoRecebimento" name="codigo" type="hidden" value="">
			<div class="mws-form-block"> 
			     
				<div class="mws-form-row box-tipo">				    
            	    <label>* Tipo</label> 				    					    
            	    <div class="mws-form-item large">				    	
            			<select id="tipo" name="tipo">
            				<option value="Reembolso">Reembolso</option>												
            				<option value="Crédito">Crédito</option>												
    					</select>    										
    			    </div>
    			</div>
    			
				<div class="mws-form-row">				    
            	    <label>* Destinado para</label> 				    					    
            	    <div class="mws-form-item large">				    	
            			<select id="destino" name="destino">
            				<option value="Contratante">Contratante</option>												
            				<option value="Venda">Venda</option>												
    					</select>    										
    			    </div>
    			</div>
    			
    			<div class="mws-form-row" id="box-contratante">				    
            	    <label>* Contratante</label> 				    					    
            	    <div class="mws-form-item large">				    	
            			<select id="contratante" name="cliente" class="full_width chzn-select">
            				<option value="">Selecione o contratante</option>													
    					</select>    										
    			    </div>
    			</div>
    			
    			<div class="mws-form-row" id="box-venda" style="display: none;">
					<label>* Código da Venda</label>
					<div class="mws-form-item large">						
						<input name="venda_destino" type="text" class="mws-textinput numero">
					</div>
				</div>	
								
    			<div class="mws-form-row" id="box-reembolso">
					<label>* Valor Reembolso (R$)</label>
					<div class="mws-form-item large">						
						<input name="valor_reembolso" type="text" value="0,00" class="mws-textinput dinheiro">
					</div>
				</div>
								
    			<div class="mws-form-row" id="box-credito">
					<label>* Valor Crédito (R$)</label>
					<div class="mws-form-item large">						
						<input readonly="readonly" name="valor_credito" type="text" value="0,00" class="mws-textinput dinheiro">
					</div>
				</div>	
								
				<div class="mws-form-row">
					<label>Câmbio (R$)</label>
					<div class="mws-form-item large">
						<input id="valorCambio" value="" name="valorcambio" type="text" class="mws-textinput dinheiro">
					</div>
				</div>	
						
		    </div>		    
		</form>
	</div>
</div>
<!-- End reembolso -->
