<div class="mws-panel grid_8" style="margin-top: 1%;">	
	<div class="mws-panel-body">
	    <div class="mws-form-inline">                                
			<div class="mws-form-cols clearfix">
			
			    <div class="mws-form-col-8-8 omega">    				
    				<!-- Upload de Imagens -->
                    <div class="mws-panel grid_8">                                        	
                    	<div class="mws-panel-header">                    
                    		<span class="mws-i-24 i-upload">Gerenciador de Arquivos</span>                    
                    	</div>
                    	<div class="mws-panel-body">                    
                    		<div id="uploader">                    
                    			<p>Seu browser não tem Flash, Silverlight, Gears, BrowserPlus ou suporte a HTML5.</p>                    
                    		</div>                    
                    	</div>                    
                    </div>							
    			</div>
    			
    			<div id="galeria" class="mws-form-col-8-8 omega">
    			</div>
    				
			</div>
		</div>   	
	</div>	
</div>
