
<!-- Paginação do crud -->
<tr id="paginacao-temp" style="display: none;">
	<td>
		<?php echo $this->paginationControl($this->paginacao, "Sliding", "/partial/paginacao.phtml"); ?>
	</td>
</tr>

<?php
if(count($this->paginacao)>0):

$aux = 0;
foreach($this->paginacao as $dados):
    $categoria = $dados->findParentRow("Model_CategoriaTransporte");
    $class = ($aux%2 == 0)?"even":"odd";
?>

<tr class="gradeX <?php echo $class;?>">
    <td width="20"><input class="checkCodigo" name="codigo[]" value="<?php echo $dados["codigo"];?>" type="checkbox"></td>        
    
    <td class="center"><?php echo stripslashes($dados["nome"]);?></td>
    <td class="center"><?php echo $categoria->nome;?></td>    
    <td>
		<a class="mws-ic-16 ic-edit edit" href="<?php echo $this->url(array("controller"=>$this->controllerName, "action"=>"cadastro", "module"=>"admin", "codigo"=>$dados["codigo"]),null,true);?>" title="Editar">&nbsp;</a>
		<a class="mws-ic-16 ic-cross delete deleteRow" href="<?php echo $this->url(array("controller"=>$this->controllerName, "action"=>"excluir", "module"=>"admin"));?>" title="Excluir">&nbsp;</a>		
    </td>
</tr>	

<?php
$aux++;
endforeach;

else :
	echo '<tr class="gradeX even"> <td style="text-align:center;" class="center" colspan="5">Nenhum registro encontrado</td>';
endif;
?>
