<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="margin:0;padding: 0px;border:solid 1px #124183;font-family: 'Verdana, Arial, Helvetica, sans-serif;font-size: 12px;">
        <div style="width:350px;background-color:#ffffff">
            <img src="http://www.lidderimobiliaria.com.br/images/default/logo-lider.jpg" />
        	<br/><br/>
	        <div style="margin:20px;text-transform: uppercase;">
	        	<?php echo $this->corpo; ?>
	        </div>
	        <div style="margin:20px;">
		        <b>Obrigado,</b><br/>
		        Lídder Imobiliária - Central de Atendimento<br/>
		        contato@lidderimobiliaria.com.br<br/>
	        </div>
        </div>
    </body>
</html>
