
<div id="grid" class="mws-panel grid_8">
	<div class="mws-panel-header">
    	<span class="mws-i-24 i-table-1">Lista de Registros</span>
    </div>
    
    <div class="mws-panel-body">
    <div class="dataTables_wrapper">
    	<div class="dataTables_length">
			<label>
				Mostrar 
				<select id="select-por-pagina" size="1">
					<option value="5" selected="selected">5</option>
					<option value="10">10</option>
					<option value="25">25</option>					
				</select> registros
    		</label>
    	</div>
    	<div class="mws-panel-toolbar top clearfix">
			<ul>				
				<li><a class="mws-ic-16 ic-arrow-refresh" href="javascript://" title="Atualizar registros">Atualizar</a></li>												
		    </ul>
		</div>
    	<div class="filter">    		    		
    		<form id="form_consulta" action="<?php echo $this->url(array("controller"=>$this->controllerName, "action"=>"cotacao-dados", "module"=>"admin"));?>" method="post" enctype="multipart/form-data">
	    		<input name="pagina" type="hidden" id="pagina">
				<input name="por-pagina" type="hidden" id="porpagina" value="5">
				<input name="ordenacao" type="hidden" id="ordenacao">
	    		
	    		<div class="mws-panel-body" style="margin:0;">
                    <div class="mws-form-inline mws-form">                                
                	    <div class="mws-form-cols clearfix boxFiltro" style="display: none;">
                	    
                	        <div class="mws-form-col-2-8 alpha">
                			    <label>Data Inicial</label>
                			    <div class="mws-form-item large">
                					 <input name="dataInicial" type="text" class="mws-textinput data" /> 
                			    </div>
                			</div>
                			
                	        <div class="mws-form-col-2-8 alpha">
                			    <label>Data Final</label>
                			    <div class="mws-form-item large">
                					 <input name="dataFinal" type="text" class="mws-textinput data" /> 
                			    </div>
                			</div>
                			                				
                	        <div class="mws-form-col-2-8 omega">				    
                        	    <label>Moeda</label> 				    					    
                        	    <div class="mws-form-item large">				    	
                        			<select name="moeda">
                        				<option value="">Todas</option>	
<?php 
if(count($this->moedas) > 0):    
	foreach($this->moedas as $moeda):				
?>                        
                    						<option value="<?php echo $moeda["codigo"];?>">
                    							<?php echo $moeda["nome"];?>
                    						</option>
<?php		
	endforeach;
endif;
?>													
                					</select>						
                			    </div>
                			</div>	                			
                		</div>
                		
                		<div class="mws-button-row">
                            <input id="buscar" type="submit" class="mws-button green" value="Buscar" style="display: none;" />
                            <input id="limparFiltro" type="button" class="mws-button blue" value="Limpar" style="display: none;" />
                            <input id="filtrar" type="button" class="mws-button orange" value="Filtrar" />
                		</div> 
                		
                	</div>
                </div>
	    		
    		</form>
    	</div>	        	
        <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>                	               	
<?php 
	if(count($this->etiquetas)>0):
	foreach($this->etiquetas as $chave => $etiqueta):		
?> 	
					<th char="<?php echo $chave;?>" class="sorting"><?php echo $etiqueta;?></th>
<?php
	endforeach; 
	endif;
?>	                
                                                           
                </tr>
            </thead>
            <tbody>
                                                
            </tbody>
        </table>
        <!-- Paginação --> 
        <div id="paginacao"></div>       	        
    </div>
    </div>
</div>
<!-- Panels End -->
