
<!-- Paginação do crud -->
<tr id="paginacao-temp" style="display: none;">
	<td>
		<?php echo $this->paginationControl($this->paginacao, "Sliding", "/partial/paginacao.phtml"); ?>
	</td>
</tr>

<?php
if(count($this->paginacao)>0):

$aux = 0;
foreach($this->paginacao as $dados):
    $class = ($aux%2 == 0)?"even":"odd";  
    $venda = $dados->findParentRow("Model_Venda");
    $contratante = $venda->findParentRow("Model_Cliente");
    $descricaoPacote = null;
    $telefone = null;
    $celular = null;
    $vendaProduto = $venda->findDependentRowSet("Model_VendaProduto")->current();
    if($vendaProduto){
        $pacote = $vendaProduto->findParentRow("Model_Pacote");
        if($pacote){
            $descricaoPacote = $pacote->descricao;
        }
    }

    $cliente = $venda->findParentRow("Model_Cliente");
?>

<tr class="gradeX <?php echo $class;?>">    
    <td class="center"><?php echo $dados->venda; ?></td>      
    <td class="center"><?php echo $dados->codigo; ?></td>               
    <td class="center"><?php echo $dados->tipo; ?></td>      
    <td class="center"><?php echo $dados->parcela; ?></td>      
    <td class="center"><?php echo $this->data($dados->datavencimento); ?></td>      
    <td class="center"><?php echo $this->NumeroParaMoeda($dados->valor); ?></td>          
    <td class="center"><?php echo $this->NumeroParaMoeda($dados->valorpago); ?></td>          
    <td class="center"><?php echo $descricaoPacote; ?></td>              
    <td>
<?php if(empty($dados->valorpago)) { ?>    
		<a target="blank" class="mws-ic-16 ic-page" href="<?php echo $this->url(array("controller"=>$this->controllerName, "action"=>"boleto", "module"=>"sac", "vendareceber"=>$dados["codigo"]),null,true);?>" title="Boleto">&nbsp;</a>
<?php } else { ?>
        <span style="color: green; font-weight: bold">PAGO</span>
<?php } ?>						
    </td>   
</tr>	

<?php
$aux++;
endforeach;

else :
	echo '<tr class="gradeX even"> <td style="text-align:center;" class="center" colspan="11">Nenhum registro encontrado</td>';
endif;
?>
